export enum eFILES {    
    PROYECTO= 'PROYECTO',
    CURP= 'CURP',
    ACTA_NACIMIENTO= 'ACTA_NACIMIENTO',
    CERTIFICADO_B='CERTIFICADO_BACHILLERATO',
    CEDULA='CEDULA_TECNICA',
    CERTIFICADO_L='CERTIFICADO_LICENCIATURA',
    SERVICIO='SERVICIO_SOCIAL',
    INGLES='LIBERACION_INGLES',
    PAGO='RECIBO',
    CERTIFICADO_R='REVALIDACION',
    RELEASED='LIBERACION'
}
