export enum RequestStatus {
    CAPTURED = 'CAPTURADA',
    SENT = 'ENVIADO',
    VERIFIED = 'VERIFICADO',
    REGISTERED = 'REGISTRADO',
    RELEASED = 'LIBERADO',
    DELIVERED = 'ENTREGADO',
    VALIDATED = 'VALIDADO',
    ASSIGNED = 'ASIGNADO',
    ACCOMPLISHED = 'REALIZADO',
    GENERATED = 'GENERADO',
}
