export enum eSocialFiles {
  SOLICITUD = 'SOLICITUD_SERVICIO_SOCIAL',
  ASIGNACION = 'CARTA_DE_ASIGNACION',
  COMPROMISO = 'CARTA_COMPROMISO',
  PRESENTACION = 'CARTA_DE_PRESENTACION',
  ACEPTACION = 'CARTA_DE_ACEPTACION',
  TARJETACONTROL = 'TARJETA_DE_CONTROL'
}
