export enum eSocialNameDocuments {
  SOLICITUD = 'ITT-POC-08-02 Solicitud de Servicio Social.pdf',
  PRESENTACION = 'ITT-POC-08-03 Carta de Presentación de Servicio Social.pdf',
  ASIGNACION = 'ITT-POC-08-04 Carta de Asignación-Plan de Trabajo.pdf',
  COMPROMISO = 'ITT-POC-08-05 Carta Compromiso de Servicio Social.pdf',
  ACEPTACION = 'ITT-POC-08-00 Carta de Aceptación de Servicio Social.pdf',
  BIMESTRAL = 'ITT-POC-08-06 Reporte Bimestral de Servicio Social.pdf',
  TARJETACONTROL = 'ITT-POC-08-07 Tarjeta de Control de Servicio Social.pdf',
  CONSTANCIA = 'ITT-POC-08-08 Constancia de Servicio Social.pdf',
  EVALUACIONRESPONSABLE = 'ITT-POC-08-09 Evaluación Responsable del Programa.pdf',
  EVALUACIONREPORTEFINAL = 'ITT-POC-08-10 Evaluación del Reporte Final.pdf',
  AUTOEVALUACION = 'ITT-POC-08-11 Autoevaluación del Alumno.pdf',
  REPORTEFINAL = 'ITT-POC-08-12 Reporte Final.pdf',

  SOLICITUD_CODE = 'ITT-POC-08-02',
  PRESENTACION_CODE = 'ITT-POC-08-03',
  ASIGNACION_CODE = 'ITT-POC-08-04',
  COMPROMISO_CODE = 'ITT-POC-08-05',
  ACEPTACION_CODE = 'ITT-POC-08-00',
  BIMESTRAL_CODE = 'ITT-POC-08-06',
  TARJETACONTROL_CODE = 'ITT-POC-08-07',
  CONSTANCIA_CODE = 'ITT-POC-08-08',
  EVALUACIONRESPONSABLE_CODE = 'ITT-POC-08-09',
  EVALUACIONREPORTEFINAL_CODE = 'ITT-POC-08-10',
  AUTOEVALUACION_CODE = 'ITT-POC-08-11',
  REPORTEFINAL_CODE = 'ITT-POC-08-12'
}
